language: python
dist: xenial
os: linux

stages:
  - black
  - test

python:
  - '3.6'
  - '3.7'
  - '3.8'
  - '3.8-dev'
  - 'nightly'

jobs:
  include:
    - stage: black
      python: '3.8'
      script:
        - black --check futaba
  allow_failures:
    - python: 'nightly'
  fast_finish: true

cache: pip

install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt

script:
  # Dispaly all lints and a report
  - pylint --reports=yes mallard

notifications:
  email:
    on_success: change
    on_failure: always
